sed -i -e 's/135poundor61kilogramb/135-pound-or-61-kilogram-b/g' $@
sed -i -e 's/1980sand1990s/1980s-and-1990s/g' $@
sed -i -e 's/afraidtotakechances/afraid-to-take-chances/g' $@
sed -i -e 's/allthethingscanbeexplained/all-the-things-can-be-explained/g' $@
sed -i -e 's/andonlybecausethesystemwontlisten/and-only-because-the-system-will-not-listen/g' $@
sed -i -e 's/approachinginfinitelygoodenough/approaching-infinitely-good-enough/g' $@
sed -i -e 's/appropriatelycareful/appropriately-careful/g' $@
sed -i -e 's/artificialintelligence/artificial-intelligence/g' $@
sed -i -e 's/assigneddiagnosis/assigned-diagnosis/g' $@
sed -i -e 's/autismspectrumdisorder/autism-spectrum-disorder/g' $@
sed -i -e 's/averagerelativetopeoplealotlikemefromthesameplacesasmewhichisalotlikehere/average-relative-to-people-a-lot-like-me-from-the-same-places-as-me-which-is-a-lot-like-here/g' $@
sed -i -e 's/basedon35yearsofhardwork/based-on-35-years-of-hard-work/g' $@
sed -i -e 's/becauseiam/because-i-am/g' $@
sed -i -e 's/becauseitsmorethanjustagame/because-it-is-more-than-just-a-game/g' $@
sed -i -e 's/becauseitsmorethanjustart/because-it-is-more-than-just-art/g' $@
sed -i -e 's/becauseitsmorethanjustspirit/because-it-is-more-than-just-spirit/g' $@
sed -i -e 's/becausethesystemwontlisten/because-the-system-will-not-listen/g' $@
sed -i -e 's/beggedfor/begged-for/g' $@
sed -i -e 's/bigb/big-b/g' $@
sed -i -e 's/bindmechanism/bind-mechanism/g' $@
sed -i -e 's/bindtag/bind-tag/g' $@
sed -i -e 's/brandonandrewmccaig/brandon-andrew-mccaig/g' $@
sed -i -e 's/buildjonathancoultonsrobotwarriors/build-jonathan-coultons-robot-warriors/g' $@
sed -i -e 's/codemonkey/code-monkey/g' $@
sed -i -e 's/consciouschoice/conscious-choice/g' $@
sed -i -e 's/considermeaprofessionalat/consider-me-a-professional-at/g' $@
sed -i -e 's/copyrightdoesntmakesenseanymore/copyright-does-not-make-sense-any-more/g' $@
sed -i -e 's/couldbealotworse/could-be-a-lot-worse/g' $@
sed -i -e 's/crushme/crush-me/g' $@
sed -i -e 's/describeverythingthatwedoinenoughdetailtomakeitunambiguoustoamachineandanotherpersonfromanothercultureorregion/describe-everything-that-we-do-in-enough-detail-to-make-it-unambiguous-to-a-machine-and-another-person-from-another-culture-or-region/g' $@
sed -i -e 's/eachindividualinexistenceever/each-individual-in-existence-ever/g' $@
sed -i -e 's/employme/employ-me/g' $@
sed -i -e 's/eventhoughthesystemisalwaystryingsohardtohearme/even-though-the-system-is-always-trying-so-hard-to-hear-me/g' $@
sed -i -e 's/everybodysufferingneedlessly/everybody-suffering-needlessly/g' $@
sed -i -e 's/everyhomosapienssapiensever/every-homo-sapiens-sapiens-ever/g' $@
sed -i -e 's/facebookinc/facebook-inc/g' $@
sed -i -e 's/ffviiinspired/ffvii-inspired/g' $@
sed -i -e 's/ffviimako/ffvii-mako/g' $@
sed -i -e 's/finalfantasy/final-fantasy/g' $@
sed -i -e 's/finalfantasy7/final-fantasy-7/g' $@
sed -i -e 's/finalfantasyseries/final-fantasy-series/g' $@
sed -i -e 's/finalfantasyvii/final-fantasy-vii/g' $@
sed -i -e 's/freefallbeer/freefall-beer/g' $@
sed -i -e 's/freefallbeermusic/freefall-beer-music/g' $@
sed -i -e 's/gpgisapopularimplementationanditsfreeineverysense/gpg-is-a-popular-implementation-and-it-is-free-in-every-sense-of-the-word/g' $@
sed -i -e 's/hurtyou/hurt-you/g' $@
sed -i -e 's/iamontosomething/i-am-on-to-something/g' $@
sed -i -e 's/iamwithyou/i-am-with-you/g' $@
sed -i -e 's/identifiedby/identified-by/g' $@
sed -i -e 's/ifiwere/if-i-were/g' $@
sed -i -e 's/includingme/including-me/g' $@
sed -i -e 's/indebtedto/indebted-to/g' $@
sed -i -e 's/itiscalled/it-is-called/g' $@
sed -i -e 's/itisnamed/it-is-named/g' $@
sed -i -e 's/justgoogleit/just-google-it/g' $@
sed -i -e 's/letalonetherestofmylife/let-alone-the-rest-of-my-life/g' $@
sed -i -e 's/littlebinpresenceonly/little-b-in-presence-only/g' $@
sed -i -e 's/makolifestream/mako-lifestream/g' $@
sed -i -e 's/manysufferingneedlessly/many-suffering-needlessly/g' $@
sed -i -e 's/metoo/me-too/g' $@
sed -i -e 's/myaudience/my-audience/g' $@
sed -i -e 's/myfamily/my-family/g' $@
sed -i -e 's/mygifttous/my-gift-to-us/g' $@
sed -i -e 's/narrowingmyscope/narrowing-my-scope/g' $@
sed -i -e 's/narrowingscope/narrowing-scope/g' $@
sed -i -e 's/neededtobeperfect/needed-to-be-perfect/g' $@
sed -i -e 's/neededtoevenbegoodenoughforyou/needed-to-even-be-good-enough-for-you/g' $@
sed -i -e 's/notbad/not-bad/g' $@
sed -i -e 's/notbadatall/not-bad-at-all/g' $@
sed -i -e 's/notgreat/not-great/g' $@
sed -i -e 's/notthathard/not-that-hard/g' $@
sed -i -e 's/onlyjustwhenithastobe/only-just-when-it-has-to-be/g' $@
sed -i -e 's/onyourside/on-your-side/g' $@
sed -i -e 's/patcheswelcome/patches-welcome/g' $@
sed -i -e 's/payme/pay-me/g' $@
sed -i -e 's/peopledependingonme/people-depending-on-me/g' $@
sed -i -e 's/peoplethatidependon/people-that-i-depend-on/g' $@
sed -i -e 's/personsufficientlydifferenttostruggleinsociety/person-sufficiently-different-to-struggle-in-society/g' $@
sed -i -e 's/predictionsforthefuture/predictions-for-the-future/g' $@
sed -i -e 's/presenttime/present-time/g' $@
sed -i -e 's/prettygood/pretty-good/g' $@
sed -i -e 's/prettygoodprivacy/pretty-good-privacy/g' $@
sed -i -e 's/prettywell/pretty-well/g' $@
sed -i -e 's/programcomputersthatcanlearnlikepeople/program-computers-that-can-learn-like-people/g' $@
sed -i -e 's/publicenemynumberone/public-enemy-number-one/g' $@
sed -i -e 's/pullrequestswelcome/pull-requests-welcome/g' $@
sed -i -e 's/puzzlingus/puzzling-us/g' $@
sed -i -e 's/reallylike/really-like/g' $@
sed -i -e 's/reallyprogressivecomparedtotoday/really-progressive-compared-to-today/g' $@
sed -i -e 's/reasonfor/reason-for/g' $@
sed -i -e 's/referredtoas/referred-to-as/g' $@
sed -i -e 's/rootcause/root-cause/g' $@
sed -i -e 's/sacrificefor/sacrifice-for/g' $@
sed -i -e 's/signatureswelcome/signatures-welcome/g' $@
sed -i -e 's/slavetothesystem/slave-to-the-system/g' $@
sed -i -e 's/socialmedia/socialmedia/g' $@
sed -i -e 's/socialmedia1.0/socialmedia-1.0/g' $@
sed -i -e 's/socialmedia2.0/socialmedia-2.0/g' $@
sed -i -e 's/softentheblow/soften-the-blow/g' $@
sed -i -e 's/startrekthenextgeneration/star-trek-the-next-generation/g' $@
sed -i -e 's/startrektng/star-trek-tng/g' $@
sed -i -e 's/steponmeandnotevenknowit/step-on-me-and-not-even-know-it/g' $@
sed -i -e 's/stillnotperfect/still-not-perfect/g' $@
sed -i -e 's/sttng/st-tng/g' $@
sed -i -e 's/sufferinginsilence/suffering-in-silence/g' $@
sed -i -e 's/syntaxisfluidofcourse/syntax-is-fluid-of-course/g' $@
sed -i -e 's/technologypermitsamazingcreationsinsecondsorminutestheresnoneedtohoardthatpowerfortherestofyourlife/technology-permits-amazing-creations-in-seconds-or-minutes-so-there-is-no-reason-to-hoard-that-power-for-the-rest-of-your-life/g' $@
sed -i -e 's/thatincludestheauthor/that-includes-the-author/g' $@
sed -i -e 's/thatis/that-is/g' $@
sed -i -e 's/thecollective/the-collective/g' $@
sed -i -e 's/theelephantintheroom/the-elephant-in-the-room/g' $@
sed -i -e 's/theonewingedangel/one-winged-angel the-one-winged-angel/g' $@
sed -i -e 's/theproblem/the-problem/g' $@
sed -i -e 's/thereader/the-reader/g' $@
sed -i -e 's/thesolutioninjeapoardy/the-solution-in-jeopardy/g' $@
sed -i -e 's/theuncomfortabletruth/the-uncomfortable-truth/g' $@
sed -i -e 's/tookthewrongchancesandlearnedtheewronglessons/took-the-wrong-chances-and-learned-the-wrong-lessons/g' $@
sed -i -e 's/trademarkisfairbutthisisprettyalternativetopreviousidentities/trademark-is-fair-but-this-is-pretty-alternative-to-previous-identities/g' $@
sed -i -e 's/trainartificialintelligence/train-artificial-intelligence/g' $@
sed -i -e 's/trustme/trust-me/g' $@
sed -i -e 's/universaltranslator/universal-translator/g' $@
sed -i -e 's/universaltranslatorjenova/universal-translator-jenova/g' $@
sed -i -e 's/uppercaseb/upper-case-b/g' $@
sed -i -e 's/watchforhistoryrewrites/watch-for-history-rewrites/g' $@
sed -i -e 's/webanalytics/web-analytics/g' $@
sed -i -e 's/whichreallyjustmeanseveryone/which-really-just-means-everyone/g' $@
sed -i -e 's/willnot/will-not/g' $@
sed -i -e 's/willnothurtyou/will-not-hurt-you/g' $@
sed -i -e 's/withthecollectivegood/with-the-collective-good/g' $@
sed -i -e 's/with-thecollectivegood/with-the-collective-good/g' $@
sed -i -e 's/withthehomeless/with-the-homeless/g' $@
sed -i -e 's/with-thehomeless/with-the-homeless/g' $@
sed -i -e 's/withtheperpetrator/with-the-perpetrator/g' $@
sed -i -e 's/with-theperpetrator/with-the-perpetrator/g' $@
sed -i -e 's/withthevictim/with-the-victim/g' $@
sed -i -e 's/with-thevictim/with-the-victim/g' $@
sed -i -e 's/withinsocialstandards/within-social-standards/g' $@
sed -i -e 's/withintolerances/within-tolerances/g' $@
sed -i -e 's/withyou/with-you/g' $@
sed -i -e 's/final-fantasy7/final-fantasy-7/g' $@
sed -i -e 's/final-fantasyseries/final-fantasy-series/g' $@
sed -i -e 's/final-fantasyvii/final-fantasy-vii/g' $@
sed -i -e 's/freefall-beermusic/freefall-beer-music/g' $@
sed -i -e 's/\blifestream\b/lifestream life-stream/g' $@
sed -i -e 's/mako-lifestream/mako-slash-lifestream/g' $@
sed -i -e 's/not-badatall/not-bad-at-all/g' $@
sed -i -e 's/pretty-goodprivacy/pretty-good-privacy/g' $@
sed -i -e 's/step-on-me-and-not-even-know-it/& meta-dr-dre-reference/g' $@
sed -i -e 's/trainartificial-intelligence/train-artificial-intelligence/g' $@
sed -i -e 's/universal-translatorjenova/universal-translator-jenova/g' $@
sed -i -e 's/will-nothurt-you/will-not-hurt-you/g' $@
sed -i -e 's/with-the-collectivegood/with-the-collective-good/g' $@
